{% set name = "dedalus" %}
{% set version = "3.0.1" %}
{% set mpi_prefix = "mpi_" + mpi %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55ce1102e17b91edffda1da916dd55455a122af708a16062f9cd8fc15448112b

build:
  number: 0
  skip: true  # [win or py<39]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - cython >=3.0.5
    - mpi4py >=2.0.0
    - numpy >=1.20.0
    - {{ mpi }}
    - fftw
    - fftw * {{ mpi_prefix }}_*
  run:
    - python
    - docopt
    - hdf5 * {{ mpi_prefix }}_*
    - h5py >=3.0 {{ mpi_prefix }}_*
    - fftw
    - fftw * {{ mpi_prefix }}_*
    - matplotlib-base
    - {{ mpi }}
    - mpi4py >=2.0.0
    - numexpr
    - {{ pin_compatible('numpy') }}
    - scipy >=1.9.1
    - py
    - pytest
    - pytest-benchmark
    - pytest-cov
    - pytest-parallel
    - openssh  # [linux]
    - xarray

test:
  imports:
    - dedalus
  commands: python3 -m dedalus test

about:
  home: https://pypi.org/project/dedalus/
  summary: A flexible framework for solving PDEs with modern spectral methods.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - kburns
