{% set name = "dedalus" %}
{% set version = "2.2207" %}
{% set mpi_prefix = "mpi_" + mpi %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 158adebf4b4939bb3d322dc81176965997f84a9ce54e020210db52eda4773dc0

build:
  number: 0
  skip: true  # [win or py<35]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - cython >=0.22
    - mpi4py >=2.0.0
    - numpy >=1.20.0
    - {{ mpi }}
    - fftw
    - fftw * {{ mpi_prefix }}_*
  run:
    - python
    - docopt
    - hdf5
    - h5py >=2.10.0
    - fftw
    - fftw * {{ mpi_prefix }}_*
    - matplotlib-base
    - {{ mpi }}
    - mpi4py >=2.0.0
    - {{ pin_compatible('numpy') }}
    - scipy >=1.4.0
    - pytest
    - pytest-benchmark
    - pytest-cov
    - pytest-parallel
    - openssh  # [linux]

test:
  imports:
    - dedalus
  commands:
    python3 -m dedalus test

about:
  home: https://pypi.org/project/dedalus/
  summary: A flexible framework for solving PDEs with modern spectral methods.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - kburns
