{% set name = "dedalus" %}
{% set version = "3.0.4" %}
{% set mpi_prefix = "mpi_" + mpi %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a63c0447c2907171c6c1534d9a09f2d537f1fbd103dcacb54a677705fe1a0dc2

build:
  number: 0
  skip: true  # [win or py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ mpi }}                              # [build_platform != target_platform and mpi == "openmpi"]
  host:
    - pip
    - python
    - setuptools
    - cython >=3.0.5
    - mpi4py >=2.0.0
    - numpy
    - {{ mpi }}
    - fftw
    - fftw * {{ mpi_prefix }}_*
  run:
    - python
    - docopt
    - hdf5 * {{ mpi_prefix }}_*
    - h5py >=3.0 {{ mpi_prefix }}_*
    - fftw
    - fftw * {{ mpi_prefix }}_*
    - matplotlib-base
    - {{ mpi }}
    - {{ pin_compatible('mpi4py') }}
    - numexpr
    - numpy
    - scipy >=1.9.1
    - py
    - pytest
    - pytest-benchmark
    - pytest-cov
    - pytest-parallel
    - openssh  # [linux]
    - xarray

test:
  imports:
    - dedalus
  commands: python3 -m dedalus test

about:
  home: https://pypi.org/project/dedalus/
  summary: A flexible framework for solving PDEs with modern spectral methods.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - kburns
