{% set name = "dedalus" %}
{% set version = "2.2207" %}

{% set mpi_prefix = "mpi_" + mpi %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 158adebf4b4939bb3d322dc81176965997f84a9ce54e020210db52eda4773dc0

build:
  number: 0
  skip: true  # [win or py>37]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - cython
    - mpi4py
    - numpy
    - fftw
    - fftw * {{ mpi_prefix }}_*

  run:
    - python
    - docopt
    - h5py
    - fftw
    - fftw * {{ mpi_prefix }}_*
    - matplotlib-base
    - mpi4py
    - {{ pin_compatible('numpy') }}
    - scipy
    - pytest
    - pytest-benchmark
    - pytest-cov

test:
  imports:
    - dedalus

about:
  home: https://pypi.org/project/dedalus/
  summary: A flexible framework for solving differential equations using spectral methods.
  license: GPL-2.0-or-later
  license_file: license.txt

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
